#ifndef __USER_CONFIG_H__
#define __USER_CONFIG_H__

#define USE_WIFI_MODE		SOFTAP_MODE
#define WIFI_CLIENTSSID		"MyWiFi"
#define WIFI_CLIENTPASSWORD	"00000000"
#define WIFI_AP_NAME		"Lamp_1"
#define WIFI_AP_PASSWORD	"00000000"
#define PLATFORM_DEBUG		true

#endif
